# Generated by Django 4.0.5 on 2022-06-13 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='web_content_size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
